from database import SessionLocal, KolKandidat, Kriteria, init_db

KRITERIA_DATA = [
    {"kode":"C1","nama":"Engagement Rate","bobot_default":0.35,"satuan":"%","deskripsi":"Rata-rata interaksi per post dibagi followers x 100%"},
    {"kode":"C2","nama":"Content Quality","bobot_default":0.20,"satuan":"Skala 1-5","deskripsi":"Skor kualitas visual dan pesan konten"},
    {"kode":"C3","nama":"Niche Relevance","bobot_default":0.20,"satuan":"Skala 1-5","deskripsi":"Kesesuaian niche dengan sektor F&B"},
    {"kode":"C4","nama":"Posting Consistency","bobot_default":0.15,"satuan":"Post/bln","deskripsi":"Jumlah unggahan dalam 30 hari terakhir"},
    {"kode":"C5","nama":"Followers Count","bobot_default":0.10,"satuan":"Akun","deskripsi":"Jumlah total pengikut akun"},
]

# Dataset 100 KOL F&B Bali — hasil pengumpulan data lapangan (Mei 2026)
# Source: Tim KOL Domestik + observasi manual peneliti
KOL_DATA = [
    {"username":"tariganlaurensia","nama_lengkap":"Cha","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":1042,"avg_likes":72,"avg_comments":9,"engagement_rate":7.52,"posting_consistency":25,"content_quality_score":4.3,"niche_relevance":3.2,"instagram_url":"https://instagram.com/tariganlaurensia"},
    {"username":"jedyumbara","nama_lengkap":"Jedy","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":4896,"avg_likes":261,"avg_comments":51,"engagement_rate":7.15,"posting_consistency":16,"content_quality_score":4.2,"niche_relevance":4.1,"instagram_url":"https://instagram.com/jedyumbara"},
    {"username":"winwinsamawa","nama_lengkap":"Winwin","niche":"Travel F&B","bio":"Bali travel diaries","followers":2953,"avg_likes":145,"avg_comments":33,"engagement_rate":6.7,"posting_consistency":23,"content_quality_score":3.6,"niche_relevance":4.5,"instagram_url":"https://instagram.com/winwinsamawa"},
    {"username":"kanyaninaa","nama_lengkap":"Nina","niche":"Travel F&B","bio":"Travel + food adventures","followers":3567,"avg_likes":188,"avg_comments":35,"engagement_rate":6.62,"posting_consistency":23,"content_quality_score":3.6,"niche_relevance":3.8,"instagram_url":"https://instagram.com/kanyaninaa"},
    {"username":"zeefoodzzz","nama_lengkap":"Zeni","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":5376,"avg_likes":240,"avg_comments":41,"engagement_rate":5.89,"posting_consistency":25,"content_quality_score":3.5,"niche_relevance":3.9,"instagram_url":"https://instagram.com/zeefoodzzz"},
    {"username":"whyuppramerta","nama_lengkap":"Wahyu","niche":"Travel F&B","bio":"Travel & culinary content","followers":1962,"avg_likes":93,"avg_comments":17,"engagement_rate":5.6,"posting_consistency":20,"content_quality_score":4.0,"niche_relevance":4.0,"instagram_url":"https://instagram.com/whyuppramerta"},
    {"username":"Mauliddian","nama_lengkap":"Dian","niche":"Travel F&B","bio":"Travel + food adventures","followers":1951,"avg_likes":68,"avg_comments":17,"engagement_rate":4.77,"posting_consistency":29,"content_quality_score":3.6,"niche_relevance":3.6,"instagram_url":"https://instagram.com/Mauliddian"},
    {"username":"elizabethclaudyaa","nama_lengkap":"Claudya","niche":"Travel F&B","bio":"Bali travel diaries","followers":1801,"avg_likes":59,"avg_comments":13,"engagement_rate":4.43,"posting_consistency":29,"content_quality_score":3.2,"niche_relevance":3.7,"instagram_url":"https://instagram.com/elizabethclaudyaa"},
    {"username":"hariwayuu","nama_lengkap":"Wayu","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":7564,"avg_likes":240,"avg_comments":43,"engagement_rate":4.14,"posting_consistency":13,"content_quality_score":3.6,"niche_relevance":3.5,"instagram_url":"https://instagram.com/hariwayuu"},
    {"username":"putu_astra98","nama_lengkap":"Astra","niche":"Travel F&B","bio":"Bali travel diaries","followers":2472,"avg_likes":78,"avg_comments":15,"engagement_rate":4.11,"posting_consistency":30,"content_quality_score":3.8,"niche_relevance":4.2,"instagram_url":"https://instagram.com/putu_astra98"},
    {"username":"kindaha_","nama_lengkap":"indah angga","niche":"Travel F&B","bio":"Bali travel diaries","followers":2338,"avg_likes":77,"avg_comments":17,"engagement_rate":4.01,"posting_consistency":25,"content_quality_score":3.5,"niche_relevance":3.8,"instagram_url":"https://instagram.com/kindaha_"},
    {"username":"jcliani","nama_lengkap":"Liani","niche":"Travel F&B","bio":"Bali travel diaries","followers":3650,"avg_likes":115,"avg_comments":20,"engagement_rate":3.94,"posting_consistency":13,"content_quality_score":3.4,"niche_relevance":3.9,"instagram_url":"https://instagram.com/jcliani"},
    {"username":"jll.aql","nama_lengkap":"Tut Jil","niche":"Travel F&B","bio":"Travel + food adventures","followers":6578,"avg_likes":196,"avg_comments":38,"engagement_rate":3.77,"posting_consistency":20,"content_quality_score":3.2,"niche_relevance":3.2,"instagram_url":"https://instagram.com/jll.aql"},
    {"username":"sunulgan","nama_lengkap":"Nia","niche":"Travel F&B","bio":"Travel + food adventures","followers":1604,"avg_likes":58,"avg_comments":10,"engagement_rate":3.75,"posting_consistency":29,"content_quality_score":3.2,"niche_relevance":3.0,"instagram_url":"https://instagram.com/sunulgan"},
    {"username":"ratich.palgunadi","nama_lengkap":"Ratih","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":7855,"avg_likes":257,"avg_comments":48,"engagement_rate":3.63,"posting_consistency":12,"content_quality_score":3.4,"niche_relevance":4.4,"instagram_url":"https://instagram.com/ratich.palgunadi"},
    {"username":"temanperjalananmuuu","nama_lengkap":"Mari","niche":"Travel F&B","bio":"Bali travel diaries","followers":2327,"avg_likes":57,"avg_comments":13,"engagement_rate":3.28,"posting_consistency":25,"content_quality_score":3.2,"niche_relevance":3.1,"instagram_url":"https://instagram.com/temanperjalananmuuu"},
    {"username":"y.udipratamaa","nama_lengkap":"Yudi","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":1286,"avg_likes":33,"avg_comments":5,"engagement_rate":3.26,"posting_consistency":20,"content_quality_score":3.3,"niche_relevance":3.4,"instagram_url":"https://instagram.com/y.udipratamaa"},
    {"username":"yourpacker_","nama_lengkap":"Ferry","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":1003,"avg_likes":27,"avg_comments":3,"engagement_rate":3.26,"posting_consistency":20,"content_quality_score":3.4,"niche_relevance":3.8,"instagram_url":"https://instagram.com/yourpacker_"},
    {"username":"fitsept","nama_lengkap":"Pitik","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":1469,"avg_likes":37,"avg_comments":5,"engagement_rate":3.23,"posting_consistency":27,"content_quality_score":2.8,"niche_relevance":3.2,"instagram_url":"https://instagram.com/fitsept"},
    {"username":"jpranata2016","nama_lengkap":"Jimmy Pranata","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":1188,"avg_likes":35,"avg_comments":5,"engagement_rate":3.17,"posting_consistency":30,"content_quality_score":3.2,"niche_relevance":4.4,"instagram_url":"https://instagram.com/jpranata2016"},
    {"username":"hahahen_explore","nama_lengkap":"Hahen","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":4222,"avg_likes":112,"avg_comments":19,"engagement_rate":3.03,"posting_consistency":24,"content_quality_score":3.0,"niche_relevance":3.1,"instagram_url":"https://instagram.com/hahahen_explore"},
    {"username":"green.tea27","nama_lengkap":"Ocha","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":19700,"avg_likes":1525,"avg_comments":312,"engagement_rate":8.61,"posting_consistency":17,"content_quality_score":4.7,"niche_relevance":4.0,"instagram_url":"https://instagram.com/green.tea27"},
    {"username":"shintantee","nama_lengkap":"Shinta","niche":"Travel F&B","bio":"Bali travel diaries","followers":19200,"avg_likes":1138,"avg_comments":169,"engagement_rate":7.07,"posting_consistency":11,"content_quality_score":4.6,"niche_relevance":3.8,"instagram_url":"https://instagram.com/shintantee"},
    {"username":"vinaarysthadewi","nama_lengkap":"Vina","niche":"Travel F&B","bio":"Bali travel diaries","followers":15700,"avg_likes":741,"avg_comments":134,"engagement_rate":6.27,"posting_consistency":8,"content_quality_score":3.9,"niche_relevance":4.0,"instagram_url":"https://instagram.com/vinaarysthadewi"},
    {"username":"luvdhika","nama_lengkap":"Surya Ardika","niche":"Travel F&B","bio":"Travel + food adventures","followers":25900,"avg_likes":1398,"avg_comments":274,"engagement_rate":5.8,"posting_consistency":14,"content_quality_score":3.7,"niche_relevance":3.8,"instagram_url":"https://instagram.com/luvdhika"},
    {"username":"jadipandu","nama_lengkap":"Pandu","niche":"Travel F&B","bio":"Bali travel diaries","followers":38000,"avg_likes":1669,"avg_comments":248,"engagement_rate":5.64,"posting_consistency":19,"content_quality_score":3.8,"niche_relevance":3.3,"instagram_url":"https://instagram.com/jadipandu"},
    {"username":"aie.licious","nama_lengkap":"Shofie","niche":"Travel F&B","bio":"Travel & culinary content","followers":10500,"avg_likes":503,"avg_comments":99,"engagement_rate":5.61,"posting_consistency":8,"content_quality_score":3.6,"niche_relevance":3.4,"instagram_url":"https://instagram.com/aie.licious"},
    {"username":"mamangelstory","nama_lengkap":"Malya & Angel","niche":"Travel F&B","bio":"Travel & culinary content","followers":35600,"avg_likes":1529,"avg_comments":291,"engagement_rate":5.46,"posting_consistency":8,"content_quality_score":3.6,"niche_relevance":4.5,"instagram_url":"https://instagram.com/mamangelstory"},
    {"username":"windatrimela","nama_lengkap":"Winda","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":24600,"avg_likes":1179,"avg_comments":201,"engagement_rate":5.46,"posting_consistency":13,"content_quality_score":3.6,"niche_relevance":3.5,"instagram_url":"https://instagram.com/windatrimela"},
    {"username":"aldi_pradana","nama_lengkap":"Aldi","niche":"Travel F&B","bio":"Travel + food adventures","followers":22900,"avg_likes":972,"avg_comments":146,"engagement_rate":5.42,"posting_consistency":19,"content_quality_score":3.9,"niche_relevance":3.8,"instagram_url":"https://instagram.com/aldi_pradana"},
    {"username":"bagusmadeaw","nama_lengkap":"Bagus","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":38100,"avg_likes":1607,"avg_comments":312,"engagement_rate":4.72,"posting_consistency":18,"content_quality_score":3.6,"niche_relevance":4.2,"instagram_url":"https://instagram.com/bagusmadeaw"},
    {"username":"laylaaa_nfadhl","nama_lengkap":"Layla","niche":"Travel F&B","bio":"Travel + food adventures","followers":10600,"avg_likes":442,"avg_comments":81,"engagement_rate":4.72,"posting_consistency":18,"content_quality_score":4.0,"niche_relevance":4.2,"instagram_url":"https://instagram.com/laylaaa_nfadhl"},
    {"username":"archel_arsenwibowo","nama_lengkap":"Archel","niche":"Travel F&B","bio":"Travel + food adventures","followers":27900,"avg_likes":1036,"avg_comments":156,"engagement_rate":4.62,"posting_consistency":10,"content_quality_score":3.8,"niche_relevance":4.0,"instagram_url":"https://instagram.com/archel_arsenwibowo"},
    {"username":"wiramaptr","nama_lengkap":"Wira","niche":"Travel F&B","bio":"Exploring Bali kuliner","followers":48000,"avg_likes":1969,"avg_comments":387,"engagement_rate":4.54,"posting_consistency":11,"content_quality_score":3.8,"niche_relevance":3.3,"instagram_url":"https://instagram.com/wiramaptr"},
    {"username":"bintaap","nama_lengkap":"Bintan","niche":"Travel F&B","bio":"Travel + food adventures","followers":15400,"avg_likes":544,"avg_comments":100,"engagement_rate":4.29,"posting_consistency":15,"content_quality_score":3.4,"niche_relevance":3.5,"instagram_url":"https://instagram.com/bintaap"},
    {"username":"friska_depari","nama_lengkap":"Friska","niche":"F&B Umum","bio":"Foodie diary Bali","followers":4082,"avg_likes":167,"avg_comments":33,"engagement_rate":5.29,"posting_consistency":21,"content_quality_score":3.5,"niche_relevance":4.7,"instagram_url":"https://instagram.com/friska_depari"},
    {"username":"anggadarmaa","nama_lengkap":"Angga","niche":"F&B Umum","bio":"Review kuliner Bali","followers":1837,"avg_likes":86,"avg_comments":13,"engagement_rate":4.82,"posting_consistency":18,"content_quality_score":3.4,"niche_relevance":4.1,"instagram_url":"https://instagram.com/anggadarmaa"},
    {"username":"hendypradanapt","nama_lengkap":"Hendy","niche":"F&B Umum","bio":"Food lover Bali edition","followers":5151,"avg_likes":177,"avg_comments":37,"engagement_rate":3.98,"posting_consistency":18,"content_quality_score":3.3,"niche_relevance":4.3,"instagram_url":"https://instagram.com/hendypradanapt"},
    {"username":"devimaharani","nama_lengkap":"Igaa Devi","niche":"F&B Umum","bio":"Bali food explorer","followers":3092,"avg_likes":108,"avg_comments":16,"engagement_rate":3.72,"posting_consistency":12,"content_quality_score":3.5,"niche_relevance":4.1,"instagram_url":"https://instagram.com/devimaharani"},
    {"username":"gekanandaap","nama_lengkap":"Ananda","niche":"F&B Umum","bio":"Food lover Bali edition","followers":3414,"avg_likes":117,"avg_comments":19,"engagement_rate":3.62,"posting_consistency":14,"content_quality_score":3.2,"niche_relevance":4.9,"instagram_url":"https://instagram.com/gekanandaap"},
    {"username":"av.ciaaa","nama_lengkap":"Cia","niche":"F&B Umum","bio":"Foodie diary Bali","followers":1019,"avg_likes":26,"avg_comments":4,"engagement_rate":3.57,"posting_consistency":19,"content_quality_score":3.3,"niche_relevance":4.4,"instagram_url":"https://instagram.com/av.ciaaa"},
    {"username":"widianii","nama_lengkap":"Widi","niche":"F&B Umum","bio":"Kuliner authentic Bali","followers":2819,"avg_likes":70,"avg_comments":15,"engagement_rate":3.22,"posting_consistency":18,"content_quality_score":3.2,"niche_relevance":4.2,"instagram_url":"https://instagram.com/widianii"},
    {"username":"sara_sw02","nama_lengkap":"Saras","niche":"F&B Umum","bio":"Bali food explorer","followers":1201,"avg_likes":33,"avg_comments":5,"engagement_rate":3.09,"posting_consistency":29,"content_quality_score":3.2,"niche_relevance":4.6,"instagram_url":"https://instagram.com/sara_sw02"},
    {"username":"gung_dyah","nama_lengkap":"Catur","niche":"F&B Umum","bio":"Kuliner authentic Bali","followers":1726,"avg_likes":39,"avg_comments":8,"engagement_rate":2.73,"posting_consistency":28,"content_quality_score":3.4,"niche_relevance":4.5,"instagram_url":"https://instagram.com/gung_dyah"},
    {"username":"delivajarum","nama_lengkap":"Deliva","niche":"F&B Umum","bio":"Food lover Bali edition","followers":1698,"avg_likes":33,"avg_comments":6,"engagement_rate":2.24,"posting_consistency":29,"content_quality_score":3.2,"niche_relevance":4.3,"instagram_url":"https://instagram.com/delivajarum"},
    {"username":"dewi.raditya","nama_lengkap":"Dewi","niche":"F&B Umum","bio":"Bali food explorer","followers":5894,"avg_likes":114,"avg_comments":13,"engagement_rate":2.11,"posting_consistency":23,"content_quality_score":3.3,"niche_relevance":5.0,"instagram_url":"https://instagram.com/dewi.raditya"},
    {"username":"alithermawan","nama_lengkap":"Alit","niche":"F&B Umum","bio":"Kuliner authentic Bali","followers":5060,"avg_likes":93,"avg_comments":16,"engagement_rate":1.94,"posting_consistency":16,"content_quality_score":3.3,"niche_relevance":4.4,"instagram_url":"https://instagram.com/alithermawan"},
    {"username":"clarisacandraswari","nama_lengkap":"Clarisa","niche":"F&B Umum","bio":"Kuliner authentic Bali","followers":4502,"avg_likes":64,"avg_comments":14,"engagement_rate":1.66,"posting_consistency":15,"content_quality_score":2.7,"niche_relevance":4.4,"instagram_url":"https://instagram.com/clarisacandraswari"},
    {"username":"andims37","nama_lengkap":"Andi","niche":"F&B Umum","bio":"Foodie diary Bali","followers":2095,"avg_likes":27,"avg_comments":4,"engagement_rate":1.65,"posting_consistency":26,"content_quality_score":2.8,"niche_relevance":4.8,"instagram_url":"https://instagram.com/andims37"},
    {"username":"thuratna","nama_lengkap":"Ratna","niche":"F&B Umum","bio":"Bali food explorer","followers":3518,"avg_likes":24,"avg_comments":3,"engagement_rate":0.81,"posting_consistency":17,"content_quality_score":2.6,"niche_relevance":4.3,"instagram_url":"https://instagram.com/thuratna"},
    {"username":"igstparta","nama_lengkap":"Gusti Parta","niche":"F&B Umum","bio":"Review kuliner Bali","followers":17700,"avg_likes":1090,"avg_comments":197,"engagement_rate":6.51,"posting_consistency":8,"content_quality_score":3.9,"niche_relevance":4.7,"instagram_url":"https://instagram.com/igstparta"},
    {"username":"marsard_","nama_lengkap":"Marsa","niche":"F&B Umum","bio":"Kuliner authentic Bali","followers":15700,"avg_likes":717,"avg_comments":128,"engagement_rate":5.73,"posting_consistency":9,"content_quality_score":4.3,"niche_relevance":4.9,"instagram_url":"https://instagram.com/marsard_"},
    {"username":"ayubiintangj","nama_lengkap":"Ayu Bintang","niche":"F&B Umum","bio":"Review kuliner Bali","followers":14000,"avg_likes":525,"avg_comments":117,"engagement_rate":5.19,"posting_consistency":11,"content_quality_score":4.0,"niche_relevance":4.7,"instagram_url":"https://instagram.com/ayubiintangj"},
    {"username":"dharma_one15","nama_lengkap":"Dharma","niche":"F&B Umum","bio":"Food lover Bali edition","followers":13600,"avg_likes":624,"avg_comments":70,"engagement_rate":4.84,"posting_consistency":9,"content_quality_score":3.5,"niche_relevance":4.6,"instagram_url":"https://instagram.com/dharma_one15"},
    {"username":"purnnayasa","nama_lengkap":"Purna Yasa","niche":"F&B Umum","bio":"Bali food explorer","followers":38400,"avg_likes":1340,"avg_comments":245,"engagement_rate":4.15,"posting_consistency":13,"content_quality_score":3.7,"niche_relevance":4.0,"instagram_url":"https://instagram.com/purnnayasa"},
    {"username":"kokoblimakan","nama_lengkap":"Koko","niche":"F&B Umum","bio":"Food lover Bali edition","followers":11500,"avg_likes":315,"avg_comments":57,"engagement_rate":3.75,"posting_consistency":18,"content_quality_score":3.2,"niche_relevance":4.5,"instagram_url":"https://instagram.com/kokoblimakan"},
    {"username":"akumakanapasaja","nama_lengkap":"Emma","niche":"F&B Umum","bio":"Kuliner authentic Bali","followers":21000,"avg_likes":621,"avg_comments":150,"engagement_rate":3.74,"posting_consistency":14,"content_quality_score":3.2,"niche_relevance":4.1,"instagram_url":"https://instagram.com/akumakanapasaja"},
    {"username":"foodbeacon","nama_lengkap":"Beacon","niche":"F&B Umum","bio":"Food lover Bali edition","followers":30000,"avg_likes":863,"avg_comments":175,"engagement_rate":3.48,"posting_consistency":15,"content_quality_score":3.7,"niche_relevance":5.0,"instagram_url":"https://instagram.com/foodbeacon"},
    {"username":"agitalifia","nama_lengkap":"Agita","niche":"F&B Umum","bio":"Food lover Bali edition","followers":13500,"avg_likes":417,"avg_comments":50,"engagement_rate":3.42,"posting_consistency":15,"content_quality_score":3.3,"niche_relevance":4.4,"instagram_url":"https://instagram.com/agitalifia"},
    {"username":"putriokasuari","nama_lengkap":"Putri","niche":"F&B Umum","bio":"Review kuliner Bali","followers":10200,"avg_likes":237,"avg_comments":62,"engagement_rate":3.19,"posting_consistency":14,"content_quality_score":3.4,"niche_relevance":4.7,"instagram_url":"https://instagram.com/putriokasuari"},
    {"username":"onikmonik","nama_lengkap":"Monik","niche":"Lifestyle F&B","bio":"Lifestyle + food Bali","followers":4924,"avg_likes":228,"avg_comments":35,"engagement_rate":6.06,"posting_consistency":13,"content_quality_score":3.7,"niche_relevance":3.1,"instagram_url":"https://instagram.com/onikmonik"},
    {"username":"evijuliantini","nama_lengkap":"Evi","niche":"Lifestyle F&B","bio":"Lifestyle + food Bali","followers":4880,"avg_likes":223,"avg_comments":32,"engagement_rate":5.13,"posting_consistency":24,"content_quality_score":3.8,"niche_relevance":3.8,"instagram_url":"https://instagram.com/evijuliantini"},
    {"username":"fairuzarum","nama_lengkap":"Fairuz","niche":"Lifestyle F&B","bio":"Aesthetic eats Bali","followers":1802,"avg_likes":75,"avg_comments":9,"engagement_rate":4.61,"posting_consistency":27,"content_quality_score":3.4,"niche_relevance":4.1,"instagram_url":"https://instagram.com/fairuzarum"},
    {"username":"yukngide","nama_lengkap":"Bli Jhon","niche":"Lifestyle F&B","bio":"Lifestyle + food Bali","followers":1025,"avg_likes":35,"avg_comments":4,"engagement_rate":4.28,"posting_consistency":18,"content_quality_score":3.3,"niche_relevance":4.5,"instagram_url":"https://instagram.com/yukngide"},
    {"username":"mahendraaditama","nama_lengkap":"Mahen","niche":"Lifestyle F&B","bio":"Lifestyle + food Bali","followers":2163,"avg_likes":75,"avg_comments":10,"engagement_rate":4.16,"posting_consistency":22,"content_quality_score":3.4,"niche_relevance":3.3,"instagram_url":"https://instagram.com/mahendraaditama"},
    {"username":"pramiswariisdp","nama_lengkap":"Pramiswari","niche":"Lifestyle F&B","bio":"Aesthetic eats Bali","followers":4262,"avg_likes":151,"avg_comments":18,"engagement_rate":3.99,"posting_consistency":17,"content_quality_score":3.5,"niche_relevance":3.1,"instagram_url":"https://instagram.com/pramiswariisdp"},
    {"username":"nndyaaisy","nama_lengkap":"Karema","niche":"Lifestyle F&B","bio":"Living the Bali life","followers":9940,"avg_likes":275,"avg_comments":71,"engagement_rate":3.82,"posting_consistency":12,"content_quality_score":3.4,"niche_relevance":4.0,"instagram_url":"https://instagram.com/nndyaaisy"},
    {"username":"gekepi","nama_lengkap":"Puspa","niche":"Lifestyle F&B","bio":"Food meets lifestyle","followers":4240,"avg_likes":118,"avg_comments":25,"engagement_rate":3.76,"posting_consistency":12,"content_quality_score":3.6,"niche_relevance":4.0,"instagram_url":"https://instagram.com/gekepi"},
    {"username":"deviagustinii","nama_lengkap":"Devi","niche":"Lifestyle F&B","bio":"Food meets lifestyle","followers":4220,"avg_likes":129,"avg_comments":20,"engagement_rate":3.52,"posting_consistency":23,"content_quality_score":3.0,"niche_relevance":4.2,"instagram_url":"https://instagram.com/deviagustinii"},
    {"username":"vieana.dpw","nama_lengkap":"Viena","niche":"Lifestyle F&B","bio":"Living the Bali life","followers":3241,"avg_likes":106,"avg_comments":15,"engagement_rate":3.41,"posting_consistency":12,"content_quality_score":3.4,"niche_relevance":3.3,"instagram_url":"https://instagram.com/vieana.dpw"},
    {"username":"mehtawulandewi","nama_lengkap":"Mehta","niche":"Lifestyle F&B","bio":"Lifestyle + food Bali","followers":6256,"avg_likes":148,"avg_comments":22,"engagement_rate":3.21,"posting_consistency":13,"content_quality_score":2.9,"niche_relevance":3.9,"instagram_url":"https://instagram.com/mehtawulandewi"},
    {"username":"idaayubellaa","nama_lengkap":"Bela","niche":"Lifestyle F&B","bio":"Living the Bali life","followers":5590,"avg_likes":97,"avg_comments":17,"engagement_rate":2.35,"posting_consistency":21,"content_quality_score":3.2,"niche_relevance":3.5,"instagram_url":"https://instagram.com/idaayubellaa"},
    {"username":"sevtiyaa2","nama_lengkap":"Sevtiya Ayu","niche":"Lifestyle F&B","bio":"Living the Bali life","followers":43200,"avg_likes":3802,"avg_comments":553,"engagement_rate":11.08,"posting_consistency":12,"content_quality_score":4.4,"niche_relevance":4.4,"instagram_url":"https://instagram.com/sevtiyaa2"},
    {"username":"adihendrasetiawan","nama_lengkap":"Adi Hendra","niche":"Lifestyle F&B","bio":"Food meets lifestyle","followers":11700,"avg_likes":788,"avg_comments":153,"engagement_rate":7.41,"posting_consistency":16,"content_quality_score":4.4,"niche_relevance":3.6,"instagram_url":"https://instagram.com/adihendrasetiawan"},
    {"username":"aikosidiprasetija_","nama_lengkap":"Aiko","niche":"Lifestyle F&B","bio":"Food meets lifestyle","followers":25700,"avg_likes":1023,"avg_comments":214,"engagement_rate":4.29,"posting_consistency":11,"content_quality_score":3.6,"niche_relevance":4.2,"instagram_url":"https://instagram.com/aikosidiprasetija_"},
    {"username":"lisanakhoiri","nama_lengkap":"Lisa","niche":"Lifestyle F&B","bio":"Food meets lifestyle","followers":15100,"avg_likes":582,"avg_comments":96,"engagement_rate":4.09,"posting_consistency":19,"content_quality_score":3.6,"niche_relevance":4.1,"instagram_url":"https://instagram.com/lisanakhoiri"},
    {"username":"aratihapsari","nama_lengkap":"Ratih Apsari","niche":"Lifestyle F&B","bio":"Lifestyle + food Bali","followers":18300,"avg_likes":551,"avg_comments":97,"engagement_rate":3.85,"posting_consistency":8,"content_quality_score":3.6,"niche_relevance":4.2,"instagram_url":"https://instagram.com/aratihapsari"},
    {"username":"indrasubawaa","nama_lengkap":"INdra","niche":"Lifestyle F&B","bio":"Aesthetic eats Bali","followers":40100,"avg_likes":1059,"avg_comments":151,"engagement_rate":3.31,"posting_consistency":11,"content_quality_score":3.1,"niche_relevance":4.4,"instagram_url":"https://instagram.com/indrasubawaa"},
    {"username":"niena_zi","nama_lengkap":"Nina","niche":"Lifestyle F&B","bio":"Food meets lifestyle","followers":10800,"avg_likes":260,"avg_comments":61,"engagement_rate":2.97,"posting_consistency":11,"content_quality_score":3.4,"niche_relevance":3.9,"instagram_url":"https://instagram.com/niena_zi"},
    {"username":"fridyericaa","nama_lengkap":"Erica","niche":"Lifestyle F&B","bio":"Lifestyle + food Bali","followers":13600,"avg_likes":271,"avg_comments":58,"engagement_rate":2.68,"posting_consistency":11,"content_quality_score":3.4,"niche_relevance":4.1,"instagram_url":"https://instagram.com/fridyericaa"},
    {"username":"made.dwiwis","nama_lengkap":"Made Dwi","niche":"Coffee Shop","bio":"Coffee enthusiast","followers":4316,"avg_likes":263,"avg_comments":66,"engagement_rate":8.14,"posting_consistency":21,"content_quality_score":3.9,"niche_relevance":4.5,"instagram_url":"https://instagram.com/made.dwiwis"},
    {"username":"susanand7922","nama_lengkap":"Susan","niche":"Coffee Shop","bio":"Specialty coffee Bali","followers":2506,"avg_likes":173,"avg_comments":29,"engagement_rate":7.62,"posting_consistency":28,"content_quality_score":3.9,"niche_relevance":4.1,"instagram_url":"https://instagram.com/susanand7922"},
    {"username":"gitanarisw","nama_lengkap":"Gita","niche":"Coffee Shop","bio":"Cafe hopping Bali","followers":1281,"avg_likes":77,"avg_comments":15,"engagement_rate":6.45,"posting_consistency":23,"content_quality_score":3.6,"niche_relevance":4.7,"instagram_url":"https://instagram.com/gitanarisw"},
    {"username":"jeremyrobki","nama_lengkap":"Jeremy","niche":"Coffee Shop","bio":"Cafe hopping Bali","followers":2722,"avg_likes":110,"avg_comments":24,"engagement_rate":4.92,"posting_consistency":19,"content_quality_score":3.3,"niche_relevance":4.1,"instagram_url":"https://instagram.com/jeremyrobki"},
    {"username":"lupawaktu_____","nama_lengkap":"Dir","niche":"Coffee Shop","bio":"Espresso lover","followers":1571,"avg_likes":66,"avg_comments":13,"engagement_rate":4.87,"posting_consistency":23,"content_quality_score":3.8,"niche_relevance":4.9,"instagram_url":"https://instagram.com/lupawaktu_____"},
    {"username":"andrismrd_","nama_lengkap":"Andri","niche":"Coffee Shop","bio":"Coffee enthusiast","followers":1571,"avg_likes":50,"avg_comments":7,"engagement_rate":3.7,"posting_consistency":29,"content_quality_score":3.0,"niche_relevance":4.8,"instagram_url":"https://instagram.com/andrismrd_"},
    {"username":"utamiijynti","nama_lengkap":"Utami","niche":"Coffee Shop","bio":"Espresso lover","followers":5073,"avg_likes":138,"avg_comments":23,"engagement_rate":3.47,"posting_consistency":25,"content_quality_score":3.3,"niche_relevance":4.0,"instagram_url":"https://instagram.com/utamiijynti"},
    {"username":"putueriksetiawan","nama_lengkap":"Erik","niche":"Coffee Shop","bio":"Bali coffee diaries","followers":2185,"avg_likes":64,"avg_comments":12,"engagement_rate":3.38,"posting_consistency":25,"content_quality_score":3.0,"niche_relevance":4.6,"instagram_url":"https://instagram.com/putueriksetiawan"},
    {"username":"adidharma_ants","nama_lengkap":"Adi Dharma","niche":"Coffee Shop","bio":"Coffee enthusiast","followers":1061,"avg_likes":31,"avg_comments":4,"engagement_rate":3.27,"posting_consistency":26,"content_quality_score":3.1,"niche_relevance":4.3,"instagram_url":"https://instagram.com/adidharma_ants"},
    {"username":"meigakarina","nama_lengkap":"Meiga","niche":"Coffee Shop","bio":"Coffee enthusiast","followers":2467,"avg_likes":58,"avg_comments":14,"engagement_rate":3.06,"posting_consistency":29,"content_quality_score":3.6,"niche_relevance":4.6,"instagram_url":"https://instagram.com/meigakarina"},
    {"username":"annetaudrey","nama_lengkap":"Audrey","niche":"Coffee Shop","bio":"Specialty coffee Bali","followers":3525,"avg_likes":77,"avg_comments":19,"engagement_rate":2.98,"posting_consistency":23,"content_quality_score":2.8,"niche_relevance":4.6,"instagram_url":"https://instagram.com/annetaudrey"},
    {"username":"iganparwata","nama_lengkap":"Gungwah","niche":"Coffee Shop","bio":"Bali coffee diaries","followers":1784,"avg_likes":37,"avg_comments":6,"engagement_rate":2.84,"posting_consistency":18,"content_quality_score":3.3,"niche_relevance":4.5,"instagram_url":"https://instagram.com/iganparwata"},
    {"username":"gallery_made_ar","nama_lengkap":"Made Arya","niche":"Coffee Shop","bio":"Specialty coffee Bali","followers":17200,"avg_likes":565,"avg_comments":87,"engagement_rate":3.65,"posting_consistency":14,"content_quality_score":3.2,"niche_relevance":4.3,"instagram_url":"https://instagram.com/gallery_made_ar"},
    {"username":"sorry_iam_latte","nama_lengkap":"Love","niche":"Coffee Shop","bio":"Bali coffee diaries","followers":14900,"avg_likes":239,"avg_comments":43,"engagement_rate":2.14,"posting_consistency":17,"content_quality_score":2.9,"niche_relevance":4.5,"instagram_url":"https://instagram.com/sorry_iam_latte"},
    {"username":"nesyaadenisaa","nama_lengkap":"Nesya","niche":"Coffee Shop","bio":"Cafe hopping Bali","followers":13700,"avg_likes":180,"avg_comments":29,"engagement_rate":1.69,"posting_consistency":12,"content_quality_score":3.5,"niche_relevance":5.0,"instagram_url":"https://instagram.com/nesyaadenisaa"},
    {"username":"akukopidankamera","nama_lengkap":"Citra","niche":"Coffee Shop","bio":"Coffee enthusiast","followers":10600,"avg_likes":32,"avg_comments":5,"engagement_rate":0.39,"posting_consistency":19,"content_quality_score":2.6,"niche_relevance":4.1,"instagram_url":"https://instagram.com/akukopidankamera"},
    {"username":"windanyargt","nama_lengkap":"Winda","niche":"Coffee Shop","bio":"Espresso lover","followers":20300,"avg_likes":52,"avg_comments":10,"engagement_rate":0.28,"posting_consistency":12,"content_quality_score":2.9,"niche_relevance":4.4,"instagram_url":"https://instagram.com/windanyargt"},
    {"username":"diahprabasari","nama_lengkap":"Diah","niche":"Coffee Shop","bio":"Cafe hopping Bali","followers":3241,"avg_likes":66,"avg_comments":9,"engagement_rate":2.38,"posting_consistency":19,"content_quality_score":2.9,"niche_relevance":4.8,"instagram_url":"https://instagram.com/diahprabasari"},
    {"username":"putrimileniaa","nama_lengkap":"Putri","niche":"Coffee Shop","bio":"Coffee enthusiast","followers":3445,"avg_likes":55,"avg_comments":11,"engagement_rate":1.96,"posting_consistency":20,"content_quality_score":3.3,"niche_relevance":4.8,"instagram_url":"https://instagram.com/putrimileniaa"},
    {"username":"yansrgn35","nama_lengkap":"Wayan","niche":"Coffee Shop","bio":"Specialty coffee Bali","followers":6062,"avg_likes":62,"avg_comments":9,"engagement_rate":1.4,"posting_consistency":12,"content_quality_score":2.4,"niche_relevance":4.1,"instagram_url":"https://instagram.com/yansrgn35"},
]

def seed():
    init_db()
    db = SessionLocal()
    try:
        if db.query(KolKandidat).count() == 0:
            for k in KRITERIA_DATA:
                db.add(Kriteria(**k))
            for kol in KOL_DATA:
                db.add(KolKandidat(**kol))
            db.commit()
            print(f"✓ Seeded {len(KOL_DATA)} KOL dan {len(KRITERIA_DATA)} kriteria")
        else:
            print("✓ Data sudah ada, skip seeding")
    finally:
        db.close()

if __name__ == "__main__":
    seed()
